### PR TITLE
[FIX] Manifest URL

### LINKED ISSUE #12: [Bug]: Wrong tag asset URL used in fetchManifest
### Describe the bug

Currently, you use this to retrieve manifest.json:
https://github.com/4Source/vare-obsidian-plugin/blob/307ba0e49a2a89ca42225e6165835039b020a050/src/util/GitHub.ts#L104-L120

This is the wrong URL. Obsidian uses the Release REST API and not the raw file. This is an important distinction, because the release asset and the ref/raw asset, don't have to be the same.
- Releases REST API: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases

### How to Reproduce

Try to add anonhostpi/obsidian-exposed-api and install 0.0.3-f

It fails, because the wrong manifest file was used

### Expected behavior

It should use the 

### OS of your device

Win11

### Obsidian Version

v1.6.3

### Plugin Version

0.3.5

### Additional context

Going to be working on a PR in a moment to fix this for ya.

### PR DESCRIPTION
**Pull request by anonhostpi**
Corrects the manifest URL to use the same URL that Obsidian does, which is the one on the Release Asset

## Describe your changes
- changes fetchReleases() to populate releases with a manifest_url
- changes fetchManifest() to accept a manifest_url

## Related Issues
Fixes #12 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~ N/A
- [x] My code fixes the feature discussed in [Related Issues](#related-issues)

### CODE REVIEW

**Comment by anonhostpi** [comment]
I've already run your workflows on my fork: https://github.com/anonhostpi/vare-obsidian-plugin/pull/2
- they ran successfully.

I've also already tested the changes on my instance against anonhostpi/obsidian-exposed-apis - 0.0.3-f (the tag that caused problems for #12)

File: src/util/GitHub.ts [hunk 1]
```diff
@@ -16,6 +16,7 @@ export interface CommunityPlugin {
 
 export type Release = {
 	url: string;
+	manifest_url: string;
```
Comment (4Source) [inline src/util/GitHub.ts:19]: I would like to keep this as the original GitHub Api Response https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-a-release

Comment (anonhostpi) [reply src/util/GitHub.ts:19]: Alright. I'll get to working on that as soon as I can. That was done to keep my changes to your code as minimal as possible, but I have another idea for implementing the patch

Comment (anonhostpi) [reply src/util/GitHub.ts]: Change implemented. Running the linter and builder, then testing the resulting plugin right now.

Comment (anonhostpi) [reply src/util/GitHub.ts]: Linter and build checks have passed: https://github.com/anonhostpi/vare-obsidian-plugin/pull/3

Testing the plugin now.

File: src/modals/PluginDataModal.ts [hunk 2]
```diff
@@ -62,18 +62,21 @@ export class PluginDataModal extends Modal {
...
 						new Notice('No releases found for this plugin. May it do not have any.');
 						return;
 					}
+					// Check a manifest could be fetched
+					const manifest =
+						await fetchManifest(undefined,undefined,releases[0]) ||
+						await fetchManifest(repo, releases[0].tag_name) ||
+						await fetchManifest(repo);
+					if (!manifest) {
+						new Notice('Plugin manifest could not be found in releases, tag ref, or default branch!');
```
Comment (anonhostpi) [inline src/modals/PluginDataModal.ts:77]: Made this more descriptive to accommodate the new behavior

File: src/modals/PluginTroubleshootingModal.ts [hunk 3]
```diff
@@ -23,7 +23,7 @@ export class PluginTroubleshootingModal extends Modal {
 		let repository = this.pluginInfo.repo.split('/').at(1) || '';
 		let manifest: PluginManifest | undefined;
 		let hasManifest = false;
-		let releases: Partial<Release>[] | undefined;
+		// let releases: Partial<Release>[] | undefined;
```
Comment (4Source) [inline src/modals/PluginTroubleshootingModal.ts:26]: Please remove this line

File: src/modals/PluginTroubleshootingModal.ts [hunk 4]
```diff
@@ -2,7 +2,7 @@ import { Modal, PluginManifest, Setting, debounce } from 'obsidian';
 import { ICON_ACCEPT, ICON_DENY } from 'src/constants';
 import VarePlugin from 'src/main';
 import { PluginInfo } from 'src/settings/SettingsInterface';
-import { Release, fetchManifest, fetchReleases, repositoryRegEx } from 'src/util/GitHub';
+import { /* Release, */ fetchManifest, fetchReleases, repositoryRegEx } from 'src/util/GitHub';
```
Comment (4Source) [inline src/modals/PluginTroubleshootingModal.ts:5]: Please Remove the Release import

**Comment by 4Source** [comment]
Ready to ship?
